### ISSUE TITLE
writing is doubled

### ISSUE THREAD

**Issue by Davronito** [j2doll/discussion#3]
Hi j2doll!
I've got this issue when using your QXlsx library in Qt android project. It works fine in main.cpp, but somehow when I save the file after these operations, the values are added repeatedly like below down the code. I'm sure that data saved in JSON file are written once. what is the problem?

        content = history.readAll();
        Buff data(content.begin(), content.end());
        JSON<Buff> json = *json::deserialize(data, json::buff2buff);
        qulonglong id = json.vecs[toBuff("payments")].size();

        for (qulonglong i = 0; i < id; ++i)
        {
            pi.amount   = toString(json.vecs[toBuff("payments")][i]->vals[toBuff("amnt")]);
            pi.day      = str2l(json.vecs[toBuff("payments")][i]->maps[toBuff("date")]->vals[toBuff("day")]);
            pi.mon      = str2l(json.vecs[toBuff("payments")][i]->maps[toBuff("date")]->vals[toBuff("mon")]);
            pi.year     = str2l(json.vecs[toBuff("payments")][i]->maps[toBuff("date")]->vals[toBuff("year")]);
            pi.hour     = str2l(json.vecs[toBuff("payments")][i]->maps[toBuff("time")]->vals[toBuff("hour")]);
            pi.min      = str2l(json.vecs[toBuff("payments")][i]->maps[toBuff("time")]->vals[toBuff("min")]);

            xlsx.write("A"+QString::number(i+1), QString::fromStdString(pi.amount));
            xlsx.write("B"+QString::number(i+1), QString::number(pi.day)+"."+QString::number(pi.mon)+
                       "."+QString::number(pi.year));
            xlsx.write("C"+QString::number(i+1), QString::number(pi.hour)+":"+QString::number(pi.min));
        }

        xlsx.saveAs(QStandardPaths::writableLocation(QStandardPaths::DownloadLocation) + "/Test.xlsx");
        history.close();
        shareUtils.share("Test.xlsx");

![photo_2019-11-15_19-23-03](https://user-images.githubusercontent.com/57801820/68950134-5d239000-07dd-11ea-8aeb-6e89244afab3.jpg)

**Comment by j2doll** [comment]
Dear @Davronito 

I do not know. If you can't do debugging yourself, can you show us the code that works?

And put QXlsx issues into QXlsx project issues. This place is private isuue to me, so no one can help you.

**Comment by Davronito** [comment]
Aah, ok! sorry, i've just registered to GitHub, i didn't know.
